Improved configuration for libblas and liblapack.
--HG--
extra : convert_revision : svn%3A0fb12191-db4b-0410-8866-e78deaee71e5/trunk%402870

diff --git a/mpqc/configure.in b/mpqc/configure.in
--- a/mpqc/configure.in
+++ b/mpqc/configure.in
@@ -876,22 +876,6 @@ if test X$PARALLEL = Xyes; then
 
 fi
 
-AC_CHECK_LIB(blas,exit)
-AC_CHECK_LIB(dgemm,exit)
-HAVE_SCALABLE_BLAS=no
-AC_CHECK_FUNC(sB_init,
-  HAVE_SCALABLE_BLAS=yes,[
-  AC_CHECK_LIB(sB_BLAS,sB_init,[
-    HAVE_SCALABLE_BLAS=yes
-    LIBS="-lsB_BLAS $LIBS"
-  ])]
-)
-if test $HAVE_SCALABLE_BLAS = yes; then
-  AC_DEFINE(HAVE_SCALABLE_BLAS)
-fi
-
-AC_CHECK_LIB(lapack,exit)
-
 AC_SUBST(HAVE_PERF)
 AC_SUBST(HAVE_MPL)
 AC_SUBST(HAVE_P4)
@@ -1108,19 +1092,15 @@ if test -n "$F77" -a "$F77" != no ; then
   if $CC -o flink -DFF=ffunc flink.c ffunc.o 1>/dev/null 2>/dev/null; then
     AC_MSG_RESULT(same as C)
     F77_SYMBOLS=symbol
-    AC_DEFINE_UNQUOTED(F77_DGEMM_SYMBOL,  dgemm)
   elif $CC -o flink -DFF=ffunc_ flink.c ffunc.o 1>/dev/null 2>/dev/null; then
     AC_MSG_RESULT(lowercase with underscore)
     F77_SYMBOLS=symbol_
-    AC_DEFINE_UNQUOTED(F77_DGEMM_SYMBOL,  dgemm_)
   elif $CC -o flink -DFF=FFUNC flink.c ffunc.o 1>/dev/null 2>/dev/null; then
     AC_MSG_RESULT(uppercase)
     F77_SYMBOLS=SYMBOL
-    AC_DEFINE_UNQUOTED(F77_DGEMM_SYMBOL,  DGEMM)
   elif $CC -o flink -DFF=FFUNC_ flink.c ffunc.o 1>/dev/null 2>/dev/null; then
     AC_MSG_RESULT(uppercase with underscore)
     F77_SYMBOLS=SYMBOL_
-    AC_DEFINE_UNQUOTED(F77_DGEMM_SYMBOL,  DGEMM_)
   else
     AC_MSG_RESULT(giving up)
     AC_MSG_ERROR(could not determine F77 symbol names)
@@ -1131,6 +1111,58 @@ else
   AC_MSG_RESULT(guessing lowercase with underscore)
 fi
 AC_SUBST(F77_SYMBOLS)
+
+dnl ----------- check for FORTRAN libraries --------------
+
+AC_LANG_SAVE
+AC_LANG_CPLUSPLUS
+LIBSSAV="$LIBS"
+LIBS="$LIBSSAV $FLIBS"
+
+LIBBLAS=""
+F77_DGEMM=`$PERL $srcdir/bin/mkf77sym.pl.in -method $F77_SYMBOLS DAXPY`
+AC_CHECK_FUNC($F77_DGEMM,HAVE_BLAS=yes,[
+  AC_CHECK_LIB(blas,$F77_DGEMM,[HAVE_BLAS=yes;LIBBLAS="-lblas"]
+  )]
+)
+AC_SUBST(HAVE_BLAS)
+if test X$HAVE_BLAS != Xyes; then
+  echo "Could not find the BLAS library.  It can be obtained at"
+  echo "http://www.netlib.org/blas"
+  exit 1
+fi
+
+LIBS="$LIBSSAV $LIBBLAS $FLIBS"
+
+LIBLAPACK=""
+F77_DGESVD=`$PERL $srcdir/bin/mkf77sym.pl.in -method $F77_SYMBOLS DGESVD`
+AC_CHECK_FUNC($F77_DGESVD,HAVE_LAPACK=yes,[
+  AC_CHECK_LIB(lapack,$F77_DGESVD,[HAVE_LAPACK=yes;LIBLAPACK="-llapack"]
+  )]
+)
+AC_SUBST(HAVE_LAPACK)
+if test X$HAVE_LAPACK != Xyes; then
+  echo "Could not find the LAPACK library.  It can be obtained at"
+  echo "http://www.netlib.org/lapack"
+  exit 1
+fi
+
+LIBS="$LIBSSAV $LIBLAPACK $LIBBLAS"
+AC_LANG_RESTORE
+
+dnl ----------- check for Scalable BLAS library --------------
+
+HAVE_SCALABLE_BLAS=no
+AC_CHECK_FUNC(sB_init,
+  HAVE_SCALABLE_BLAS=yes,[
+  AC_CHECK_LIB(sB_BLAS,sB_init,[
+    HAVE_SCALABLE_BLAS=yes
+    LIBS="-lsB_BLAS $LIBS"
+  ])]
+)
+if test $HAVE_SCALABLE_BLAS = yes; then
+  AC_DEFINE(HAVE_SCALABLE_BLAS)
+fi
 
 dnl ----------- NIAMA library checks --------------
 
